#  Need to deploy the CSI driver for pureflash or allflash pure storage which are components included now within portworx operator
# https://github.com/openshift-instruqt/instruqt/blob/master/instruqt-tracks/gitops-pipelines/scripts/operator/subscription.yaml
# List operators in marketplace: oc get packagemanifests -n openshift-marketplace |grep portworx
# This is broken. Operator deployment in below yaml fails but GUI works.
# Operator must be in "openshift-operators" name space for proper deployment
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators
---  
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: portworx-og
  namespace: openshift-operators
spec:
  targetNamespaces:
  - openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: portworx-certified
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: portworx-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: portworx-operator.v23.10.1
