# Secrets needed to deploy nodes and control machine-sets
# https://docs.portworx.com/portworx-enterprise/install-portworx/openshift/vsphere/openshift-vsphere
# Below value is basic base64 hash.   Ex: echo '<vcenter-server-user>' | base64
# Issue : We need to polish this prep step up related to limited role within vCenter for use by "cloud drive"
# https://docs.portworx.com/portworx-enterprise/install-portworx/openshift/vsphere/openshift-vsphere-with-console-plugin#grant-the-required-cloud-permissions
# 
apiVersion: v1
kind: Secret
metadata:
    name: px-vsphere-secret
    namespace: k8-storage
type: Opaque
data:
    VSPHERE_USER: YWRtaW5pc3RyYXRvckB2c3BoZXJlLmxvY2FsCg==
    VSPHERE_PASSWORD: cDlWIWo4MlhmMwo=