apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  # Create Rolebindings for Groups in GroupSync Below
  # TODO: Discuss w/ team how we should include these..
  - rolebinding-group-sync.yaml
patches:
  # Inject LDAP Auth Config
  - patch: |-
      - op: replace
        path: /spec/identityProviders/1/ldap/bindDN
        value: 'CN=svc-adbind,OU=Users,OU=Sirius,DC=ad,DC=pod1,DC=nucpod,DC=xyz'
      - op: replace
        path: /spec/identityProviders/1/ldap/url
        value: 'ldap://ad.pod1.nucpod.xyz:389/DC=ad,DC=pod1,DC=nucpod,DC=xyz?sAMAccountName?sub'
    target:
      kind: OAuth
      name: cluster
  # Inject LDAP GroupSync Config
  - patch: |-
      - op: replace
        path: /spec/providers/0/ldap/url
        value: 'ldap://ad.pod1.nucpod.xyz:389'
      - op: replace
        path: /spec/providers/0/ldap/augmentedActiveDirectory/groupsQuery/baseDN
        value: 'DC=ad,DC=pod1,DC=nucpod,DC=xyz'
      - op: replace
        path: /spec/providers/0/ldap/augmentedActiveDirectory/usersQuery/baseDN
        value: 'DC=ad,DC=pod1,DC=nucpod,DC=xyz'
      - op: add
        path: /spec/providers/0/ldap/whitelist/-
        value: 'CN=OpenShift-Admins,OU=Groups,OU=Sirius,DC=ad,DC=pod1,DC=nucpod,DC=xyz'
      - op: add
        path: /spec/providers/0/ldap/whitelist/-
        value: 'CN=OpenShift-ReadOnly,OU=Groups,OU=Sirius,DC=ad,DC=pod1,DC=nucpod,DC=xyz'
    target:
      kind: GroupSync
      name: ldap
