# Storage Class definiton for iSCSI volume and claim types
# 
kind: StorageClass 
apiVersion: storage.k8s.io/v1 
metadata: 
 name: iscsi-block-sc
  labels: 
    kubernetes.io/cluster-service: “true” 
provisioner: pure-provisioner
parameters: 
  backend: block