apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
- target:
    kind: ConfigMap
    name: custom-ca
  patch: |
    - op: replace
      path: /data/ca-bundle.crt
      value: |
        -----BEGIN CERTIFICATE-----
        MIIDiTCCAnGgAwIBAgIQGvn6axyB+blHF9FZlmGdsjANBgkqhkiG9w0BAQsFADBL
        MRUwEwYKCZImiZPyLGQBGRYFbG9jYWwxFDASBgoJkiaJk/IsZAEZFgRsYWJzMRww
        GgYDVQQDExNsYWJzLVZIMUMyMDIyREMyLUNBMB4XDTIzMTAwNjEzMjM1NloXDTM4
        MTAwNjEzMzM1NlowSzEVMBMGCgmSJomT8ixkARkWBWxvY2FsMRQwEgYKCZImiZPy
        LGQBGRYEbGFiczEcMBoGA1UEAxMTbGFicy1WSDFDMjAyMkRDMi1DQTCCASIwDQYJ
        KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMP9VgycBT0X2oYOlSYOC/h02RCu9f5Y
        tRTX2EMnEU3C/m2pPw4sGEgIo31LBPmBx1c4vXacO9ISxsLwcC8NqIq+M6n0hDzC
        Geuxt12kGTsgZjHhlrkUsJkU/sw2xPSS6YtHIX3uCazKU0aqSVSwdcqzbeC9jgSw
        LHiZg5BPAEA0Z1Cj976kuwWfzJyPUig0EmTR+925yIv1eIRAs0CrwCxP1hno7VRy
        w2akOFXC/MsFqkWfFKh3Ml5g6yHBRtQjYJwksixoVaSbfASGhzM/BNlD4xjRR+Dp
        xEtUz+g3HwrhdLgAcURlZUZ54OicgDAAa8EWr9cpMpKsGuiLPfDKDZ0CAwEAAaNp
        MGcwEwYJKwYBBAGCNxQCBAYeBABDAEEwDgYDVR0PAQH/BAQDAgGGMA8GA1UdEwEB
        /wQFMAMBAf8wHQYDVR0OBBYEFICQhH08LFHzbNydZ4uoBv1PTJtOMBAGCSsGAQQB
        gjcVAQQDAgEAMA0GCSqGSIb3DQEBCwUAA4IBAQC0/q24kLPbxXz8R7wCj7yQWHuM
        Cb/7aoO8LFF3I/OlXOeCeR2INpvFgblyu1t3f9jdx5hcK3jl4zqnoI55T+34Sh6A
        ZpaOZ7Ple5nxa9merY3ooBg5xxAS/B0NCQ7t7ZNQgaikE3Fpo5fWaUio1+XZS36n
        LfQGWllPIiZOfJNufqX/UNZY/vesPODy2ls8ttiistrJGW/+jfGV638XO8Aeh0+Z
        RvazgG8ErUFI22OiHJkajTQOypOEVAlp7fc0u77Vm1EMVqxpA/Wpx2BRWiASjaW8
        qyVNan+Xo8WIHf0m9wyh0KF3zSffodvVDbV+vMDI8a+dfeiflNqf1tIzq6P+
        -----END CERTIFICATE-----