# Documentation: https://external-secrets.io/latest/api/clustersecretstore/
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: external-secrets-azure
spec:
  provider:
    azurekv:
      tenantId: replace_in_overlay
      vaultUrl: replace_in_overlay
      authSecretRef:
        clientId:
          name: external-secrets-azure
          namespace: external-secrets
          key: ClientID
        clientSecret:
          name: external-secrets-azure
          namespace: external-secrets
          key: ClientSecret
  # Namespaces that are allowed to use this ClusterSecretStore for ExternalSecrets
  conditions:
    - namespaces:
        - openshift-gitops
        - openshift-ingress
        - openshift-config
        - group-sync-operator
        - k8-storage
