# Apply OpenShift SCCs to allow extrnal-secrets' privileged pods
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-secrets-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: external-secrets
  namespace: external-secrets
- kind: ServiceAccount
  name: external-secrets-cert-controller
  namespace: external-secrets
- kind: ServiceAccount
  name: external-secrets-webhook
  namespace: external-secrets
