apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manage-external-secrets
  annotations:
    kubernetes.io/description: |-
      Use this in RoleBindings to allow creating and managing ExternalSecrets.
      Especially useful for giving the Argo CD service account this permission
      within the namespaces it manages.
    argocd.argoproj.io/sync-wave: "-1" # prevent deletion until all other resources are deleted
rules:
- apiGroups: ["external-secrets.io"]
  resources: ["externalsecrets"]
  verbs: ["*"]