apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Give Argo CD permissions to deploy the external-secrets operator
- rolebinding-argocd.yaml
# Give external-secrets the permissions its pods need to start
- clusterrolebinding-external-secrets-privileged.yaml
# Create a ClusterSecretStore to connect to Azure Key Vault
- clustersecretstore-external-secrets-azure.yaml
# Create a ClusteRole for namespaced RoleBindings to allow creation of their ExternalSecrets
- clusterrole-manage-external-secrets.yaml

helmCharts:
- name: external-secrets
  includeCRDs: true
  releaseName: external-secrets
  version: v0.9.4
  repo: https://charts.external-secrets.io
  namespace: external-secrets
