apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-bastion
  nameSpace: openshift-image-registry
spec:
  StorageClassName: "nfs-client"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 150Gi
  volumeName: pv-nfs-bastion
