---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: htpasswd-file
  namespace: openshift-config
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-azure
  target:
    name: htpasswd-file
  data:
    - secretKey: htpasswd
      remoteRef:
        key: htpasswd-file
