---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ldap-bind
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Create secrets first
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-azure
  target:
    name: ldap-bind
  data:
    - secretKey: bindPassword
      remoteRef:
        key: ldap-bind-password
