apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentication
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3" # After ocp-tls-certificates
spec:
  destination:
    namespace: openshift-config
    name: in-cluster
  project: cluster-config
  source:
    path: replace_in_overlay
    repoURL: replace_in_overlay
    targetRevision: replace_in_overlay
  syncPolicy:
    # Don't delete deployed resources if this app is deleted
    automated:
      prune: false
