apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1" # After argocd app
spec:
  destination:
    namespace: external-secrets
    name: in-cluster
  project: cluster-config
  source:
    path: replace_in_overlay
    repoURL: replace_in_overlay
    targetRevision: replace_in_overlay
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    # Don't delete deployed resources if this app is deleted
    automated:
      prune: false
