apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ingress-certificate
  namespace: openshift-ingress
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets-azure
  target:
    name: ingress-certificate # Name of the Secret to create in K8s (usually matches ExternalSecret name, in metadata)
  data:
  - secretKey: tls.crt # Name of the key to add to the Secret in K8s
    remoteRef:
      key: ingress-tls-crt # Name of the Secret in your Azure Key Vault
  - secretKey: tls.key # Name of the key to add to the Secret in K8s
    remoteRef:
      key: ingress-tls-key # Name of the Secret in your Azure Key Vault
