apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd
  namespace: openshift-ingress
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # prevent deletion until all other resources are deleted
subjects:
- kind: ServiceAccount
  name: openshift-gitops-argocd-application-controller
  namespace: openshift-gitops
roleRef:
  kind: ClusterRole
  name: manage-external-secrets
  apiGroup: rbac.authorization.k8s.io
