apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storage-namespace.yaml
  - machine-set-storage-vm.yaml
  # - iscsi-vm.yaml  # Add other storage requirment of machine modification to reflect storage types