# In order for Argo CD to install external-secrets, it needs to be able
# to create/manage CRDs, Validating Webhook Configurations, and ClusterSecretStores
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-create-global-resources
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - validatingwebhookconfigurations
  verbs:
  - '*'
- apiGroups:
  - external-secrets.io
  resources:
  - clustersecretstores
  verbs:
  - '*'
