#  Need to deploy the CSI driver for pureflash or allflash pure storage which are components included now within portworx operator
# https://github.com/openshift-instruqt/instruqt/blob/master/instruqt-tracks/gitops-pipelines/scripts/operator/subscription.yaml
# List operators in marketplace: oc get packagemanifests -n openshift-marketplace |grep odf
# This is broken. Operator deployment in below yaml fails but GUI works.
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: odf-operator
  namespace: k8-storage
spec:
  channel: stable
  installPlanApproval: Automatic
  name: odf-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace