kind: Pod
apiVersion: v1
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  volumes:
  - name: netapp-vol
    persistentVolumeClaim:
      claimName: netapp-claim-block
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: netapp-vol
      mountPath: /data
    ports:
    - containerPort: 80