# Secret service account
#   https://docs.netapp.com/us-en/astra-control-center/get-started/setup_overview.html#create-a-cluster-role-kubeconfig
apiVersion: v1
kind: ServiceAccount
metadata:
  name: astracontrol-service-account
  namespace: default
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-astracontrol-service-account
  namespace: netapp-acc-operator
  annotations:
    kubernetes.io/service-account.name: "astracontrol-service-account"
type: kubernetes.io/service-account-token