#  Need to deploy the CSI driver to bind to NetApp storage which are components included now within Astra Control Center
# https://github.com/openshift-instruqt/instruqt/blob/master/instruqt-tracks/gitops-pipelines/scripts/operator/subscription.yaml
# List operators in marketplace: oc get packagemanifests -n openshift-marketplace |grep acc
# This is broken. Operator search not clear which one to use/deployment in below yaml fails but GUI works.
apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    operators.operatorframework.io/builder: operator-sdk-v1.14.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
    olm.targetNamespaces: ''
    operatorframework.io/properties: >-
      {"properties":[{"type":"olm.gvk","value":{"group":"astra.netapp.io","kind":"AstraControlCenter","version":"v1"}},{"type":"olm.package","value":{"packageName":"acc-operator","version":"23.10.0"}}]}
    support: NetApp
    alm-examples: |-
      [
        {
          "apiVersion": "astra.netapp.io/v1",
          "kind": "AstraControlCenter",
          "metadata": {
            "name": "astra"
          },
          "spec": {
            "accountName": "Example",
            "additionalValues": {},
            "astraAddress": "astra.example.com",
            "astraResourcesScaler": "Default",
            "astraVersion": "23.10.0-68",
            "autoSupport": {
              "enrolled": true
            },
            "crds": {
              "externalCertManager": false,
              "externalTraefik": false
            },
            "email": "admin@example.com",
            "firstName": "SRE",
            "imageRegistry": {
              "name": "example.registry/astra",
              "secret": "astra-registry-cred"
            },
            "ingressType": "Generic",
            "lastName": "Admin",
            "storageClass": "ontap-gold",
            "volumeReclaimPolicy": "Retain"
          }
        }
      ]
    capabilities: Basic Install
    olm.operatorNamespace: netapp-acc-operator
    createdAt: '2023-11-07'
    categories: 'Storage, Developer Tools'
    operatorframework.io/suggested-namespace: netapp-acc-operator
    description: 'Install, configure and monitor Astra Control Center'
    olm.operatorGroup: netapp-acc-operator-vmlsx
  resourceVersion: '27034244'
  name: acc-operator.v23.10.0
  uid: 4c228ec5-723c-43d9-acf3-afd234233649
  creationTimestamp: '2023-11-21T16:18:08Z'
  generation: 1
  managedFields:
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:createdAt': {}
            'f:alm-examples': {}
            'f:description': {}
            'f:capabilities': {}
            .: {}
            'f:categories': {}
            'f:operatorframework.io/suggested-namespace': {}
            'f:operators.operatorframework.io/project_layout': {}
            'f:operatorframework.io/properties': {}
            'f:operators.operatorframework.io/builder': {}
            'f:support': {}
        'f:spec':
          'f:version': {}
          'f:maturity': {}
          'f:provider':
            .: {}
            'f:name': {}
            'f:url': {}
          'f:links': {}
          'f:install':
            .: {}
            'f:spec':
              .: {}
              'f:clusterPermissions': {}
              'f:deployments': {}
              'f:permissions': {}
            'f:strategy': {}
          'f:description': {}
          'f:installModes': {}
          'f:minKubeVersion': {}
          'f:icon': {}
          'f:customresourcedefinitions':
            .: {}
            'f:owned': {}
          .: {}
          'f:relatedImages': {}
          'f:cleanup':
            .: {}
            'f:enabled': {}
          'f:apiservicedefinitions': {}
          'f:displayName': {}
          'f:keywords': {}
      manager: catalog
      operation: Update
      time: '2023-11-21T16:18:08Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:olm.operatorGroup': {}
            'f:olm.operatorNamespace': {}
            'f:olm.targetNamespaces': {}
          'f:labels':
            .: {}
            'f:operators.coreos.com/acc-operator.netapp-acc-operator': {}
      manager: olm
      operation: Update
      time: '2023-11-21T16:18:08Z'
    - apiVersion: operators.coreos.com/v1alpha1
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:lastUpdateTime': {}
          'f:requirementStatus': {}
          'f:phase': {}
          'f:lastTransitionTime': {}
          'f:conditions': {}
          .: {}
          'f:cleanup': {}
          'f:message': {}
          'f:reason': {}
      manager: olm
      operation: Update
      subresource: status
      time: '2023-11-21T16:18:50Z'
  namespace: netapp-acc-operator
  labels:
    operators.coreos.com/acc-operator.netapp-acc-operator: ''
spec:
  customresourcedefinitions:
    owned:
      - description: AstraControlCenter is the Schema for the astracontrolcenters API.
        displayName: Astra Control Center
        kind: AstraControlCenter
        name: astracontrolcenters.astra.netapp.io
        version: v1
  relatedImages:
    - image: >-
        registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:7a8b4b60345cff84089835a561b4b65c5eccb4585283314c90ce2108c063c87d
      name: ose-kube-rbac-proxy
    - image: >-
        registry.connect.redhat.com/netapp/acc-operator-22-8-0@sha256:8a03fb36993ece687e2976a2861a1a6bd5e8a2d2cff19329eda3d84dc0457ef2
      name: acc-operator
    - image: >-
        registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:7a8b4b60345cff84089835a561b4b65c5eccb4585283314c90ce2108c063c87d
      name: kube-rbac-proxy
    - image: >-
        registry.connect.redhat.com/netapp/acc-operator-22-8-0@sha256:8a03fb36993ece687e2976a2861a1a6bd5e8a2d2cff19329eda3d84dc0457ef2
      name: manager
  cleanup:
    enabled: false
  apiservicedefinitions: {}
  keywords:
    - application data management
    - storage
  displayName: netapp-acc-operator
  provider:
    name: NetApp
    url: 'http://www.netapp.com'
  maturity: stable
  installModes:
    - supported: false
      type: OwnNamespace
    - supported: false
      type: SingleNamespace
    - supported: false
      type: MultiNamespace
    - supported: true
      type: AllNamespaces
  version: 23.10.0
  icon:
    - base64data: >-
        iVBORw0KGgoAAAANSUhEUgAAADcAAAA3CAYAAACo29JGAAAABHNCSVQICAgIfAhkiAAACRtJREFUaEPNmguUVWMUx/eZ0js9TA9Fip6m1DSREsmr5JFICnlEWF6FZSVaSIXC6sEijx4sj/JalPKoTBGJZqa8Vio1FBq96KX38fvPvbe5M6a5Z+79btprnXXPvfec/X3/b+/933t/53jmWHxbWtlsb1czrx2q65v5dfnk8PRZm+NPflvHJ4enz9/4vtis7Meetd7ucjqeC2W+LWlqtq87k+WwMzjKx6F3FyDnm6XMMts/07OMlXHoKHRLQuCwUntAPY7GMxOdSDH3zwHsfYDMild3XOB8yz6RgUdhqQvjHTjgfT7XvY01h3rWZnnAew5cVipwvi1uwEAjuPsqjpTSDhb/9f5e7p3EYg7zrO3vQfUEBoe1iCV/OgNUC6o8Cdf9xfg9PUufF0R3IHAA64WyV+MkiiDzKM01Ip5ricVpsW6KCc63rOtZrYkoinltrMEc/k8sejdhwZdK0lnihMMWe8vhpByrSrkConnzYEoPCs63nI7kG+jYq+h4Rg7V+f/Aax2x4JLilBYLjvx1DPkrmxtqOZyJ2TU1zF7Z7FQl8beG6gaArdcWVfwfcL6trmC2eSEXtnE6ix6Q7OvHmfXJNZuxxalqAOaY1QRgo53RiosBl/UwrviQ49HNPjnB7NwjzT4C2Pk/O1cPQHJgBnMvkELgIBDc0Kem85iFY9nYyqxGGbMN+yifv3OsXOr8v3HPprgnhXlIioKbwG83Ox+5blmz3DSz3TB4OYas/73ZRkA6F38c1hv0H3BYjYDw8ReP5XUsirepDc2+pKPpSEd02WqzWa7jLt96xFxKC9gzt5DlSNZTAXaFY1ghdY/XM7sTjx/+h9lQ2rqn1ps9yHly5GXqz+sOgPNtWVWzHfhskqqQnOZmaZBwkx/MfqKh+JYFPuWn5EDDfGZVq3vWZEt+zOGSffh4I+HR6h9h1q6S2ftapyjZTVbJ22N2LODWQyxVaCgqLi18zUVw2OIdZn+oAUhY+mK9qWFwDlyyHqSxoIlZKgD/YfGGsHswaZNZKyz2VTOzD4mxXsTajOPNzsZR2iwzW04NPOAosxG4bVUAr9tNTK7gM1GA/jSIpY9Hj8ZsvA0J079oKK+lWWVOxIg7AbiXYzpW7FXd7C7ATmCYQcTeY4D5gN+7h7unClwvJt0Gg9aBSfcnajmlBb8W4LK6AezDRNXl3/8kk76Vyd/0q1lTLDa4jtkeZrqdSXfCIiuwjGJvbuOQa5YF1GjS0kpicAJ98FjO73dFNP75Avews4qkEhPeTEwpUSuXSW7A7eZuJc8BLCLHlzPrXMVsMm4r+R2L18Gty1H/ukt/QwCX7TZxT8ECvSmQVUPKJSPC3POttow426WtkbD0xDVfa2j2glwW13UmJHTAvYe+HgnpVLyJJXWcB+t1IVF/AfNFasjexJxcVpaVDM8zG0euk8ym5jyV62XdudtCjPkNyT5RToGzBU69UOtSgcugxTuZCXXBtU4BUAPcTAQikCKDddD+SbDhNr70wYrPsDf7K79lMvl23KtFGMw+zzNY6zj4bB4sW5tPEdEu7qnAIqzBjb8G6KeAFuAsWrdSib9I4LTrS+QHlInHml2CJSozAcWHjCEQmoBKqoWs+hLOtfICm0vS/pMvGVE7c5kQShr7tmkk8vX8dwSgtEhnsFg90Z3OAuxAZ0WU+yzafo636QP70boFl18ETj1QsB1iUXY2OasFg+9hQMWRctUcuRSHase8KH9qjEUXsBk9m//6/VIwrTtTzYYdDRDy3jysGRG5rbwiA6CXEIttOK/CCimlrGKcdBYjOl5LBrqr9JZTsh3JxE4nEZ/ImuSDBHQkN8mKM9iBu4FVluVWY7mNAE6Pstx83LAZwFsy2Q38J2/oSqzKNQUkulf5kbVXD/gYcSrdwSUvvpiLHqAZABVDnXCp04jDFjDiTvz1PZiyH/nuUizwIgy6lphbhJVk9bYcA2HGlzaavdnQrBsLVZ5F+xHrLOAaHXLzn6PSR3BQkSuXKs99xFLxVMaR3EheG88WzChWepjCGZGLjYUtK2BKjGND+f05yETyCF5wD4lfaeBFwLqTfLacgr5rnelUYVwTEGXCG1K1ON+EJZXamuCKq7CgSEjurWSv8z0U1rqmltMO/XmB01OawU7A9YX2FT9PY5WJWGEEVumAy64BkAriiHwFyTTAhPMhoCGkhLuwnCzeHzeeRrw6EfZUnNaWaymjtKWQCTt2IP4kWyGBaljv6lyzd4lDJfQpNP0ikqPEOLDH51x/FoQSaYvcgFNtqa4gRXyMzyQg7bHQ9EYAAZzykshBiVoyg9/HUJE8QFE8mti7jVSgNKBO4AkSvMoy5bO/cM2LV8WRsIvO24de/dRIP+eGVPrXDFnsWdwyJ1xRaMdrHRZdwvf2pIMs8qTARG8SiT1vB/BM5vROkUY3rvUO93O6l7i7hY/n4tIT5KYNkIwKgCrf0shS6W3HVVOdkkfRWUR34ouJ/BSV5Ml5kjOHcqsTFu0MqWSSwFXJnJPwI++DLSvJsRIu2XzrATBJ3f0aQun6ILteakYH8ULDI+Q5VRxJkZBLSnUUuJyGMIF2m93vW3alAnkXUskm7hRfIpNPYEjnon1LrzmbQ/mF7KHZcU6FQdey46y6UXXood5xDhHLUnxmL5SWhOfemyCV6uFqJSlkIvr3GmO1cBdcDIE43VOJdjv1cGfinmqNkkImMZ7yhKyn53ObvgR3utOQuBenGE3CvptnhEroboVCtkaHmM/nwu6ZnCerTwPuDpebQPmzDf5kNbKgPBM/DfbMxIJqUg5T0TNxD4u1LbI3H5pujLcZcgawMi8cpsg0rcsBxutTxUvMigQLXgnAydyeWGHtdoWoQlL6lfSaRkzLFbhodgfOtUKU9P+3+LQWZXlFqvWiWDOJabkCgKo/vZnOWTTWDAv/T2yV7+ZZWnj/ouSbA4MLsegKdoO2DOR0KCBJWodKfJKj9yh7E2N4qEijGExKBa7Aiqpk9o3ke3+OJL6aqFcRPZ5llBke/ZZCMGgJtjhUMyehYjyDdQ46YCmuo4EuMwhQcT9fjstyRScISGqrlAvIi3rPWUCD7WAXViR3+wzn5x1n++B/f8e5OCscTm+n/wusAOrCupOS2gAAAABJRU5ErkJggg==
      mediatype: image/png
  minKubeVersion: 1.19.0
  links:
    - name: Acc Operator
      url: 'https://acc-operator.domain'
  install:
    spec:
      clusterPermissions:
        - rules:
            - apiGroups:
                - '*'
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - authentication.k8s.io
              resources:
                - tokenreviews
              verbs:
                - create
            - apiGroups:
                - authorization.k8s.io
              resources:
                - subjectaccessreviews
              verbs:
                - create
          serviceAccountName: default
      deployments:
        - label:
            control-plane: controller-manager
          name: acc-operator-controller-manager
          spec:
            replicas: 1
            selector:
              matchLabels:
                control-plane: controller-manager
            strategy:
              type: Recreate
            template:
              metadata:
                creationTimestamp: null
                labels:
                  control-plane: controller-manager
              spec:
                containers:
                  - args:
                      - '--secure-listen-address=0.0.0.0:8443'
                      - '--upstream=http://127.0.0.1:8080/'
                      - '--logtostderr=true'
                      - '--v=10'
                    image: >-
                      registry.redhat.io/openshift4/ose-kube-rbac-proxy@sha256:7a8b4b60345cff84089835a561b4b65c5eccb4585283314c90ce2108c063c87d
                    name: kube-rbac-proxy
                    ports:
                      - containerPort: 8443
                        name: https
                        protocol: TCP
                    resources: {}
                  - resources:
                      limits:
                        cpu: 300m
                        memory: 750Mi
                      requests:
                        cpu: 100m
                        memory: 75Mi
                    readinessProbe:
                      httpGet:
                        path: /readyz
                        port: 8081
                      initialDelaySeconds: 5
                      periodSeconds: 10
                    name: manager
                    command:
                      - /manager
                    livenessProbe:
                      httpGet:
                        path: /healthz
                        port: 8081
                      initialDelaySeconds: 15
                      periodSeconds: 20
                    env:
                      - name: ACCOP_LOG_LEVEL
                        value: '2'
                      - name: ACCOP_HELM_INSTALLTIMEOUT
                        value: 5m
                    securityContext:
                      allowPrivilegeEscalation: false
                    imagePullPolicy: IfNotPresent
                    image: >-
                      registry.connect.redhat.com/netapp/acc-operator-22-8-0@sha256:8a03fb36993ece687e2976a2861a1a6bd5e8a2d2cff19329eda3d84dc0457ef2
                    args:
                      - '--health-probe-bind-address=:8081'
                      - '--metrics-bind-address=127.0.0.1:8080'
                      - '--leader-elect'
                securityContext:
                  runAsUser: 65532
                terminationGracePeriodSeconds: 10
      permissions:
        - rules:
            - apiGroups:
                - ''
                - coordination.k8s.io
              resources:
                - configmaps
                - leases
              verbs:
                - get
                - list
                - watch
                - create
                - update
                - patch
                - delete
            - apiGroups:
                - ''
              resources:
                - events
              verbs:
                - create
                - patch
          serviceAccountName: default
    strategy: deployment
  description: >
    Astra Control is an application-aware data management solution that manages,
    protects and moves data-rich Kubernetes workloads in both public clouds and
    on-premises.


    Astra Control enables data protection, disaster recovery, and migration for
    your Kubernetes workloads, leveraging NetApp's industry-leading data
    management technology

    for snapshots, backups, replication and cloning.


    ### How to deploy Astra Control


    Refer to [Installation
    Procedure](https://docs.netapp.com/us-en/astra-control-center/get-started/acc_operatorhub_install.html)
    to deploy Astra Control Center using

    the Operator.


    ### Documentation


    Refer to [Astra Control Center
    Documentation](https://docs.netapp.com/us-en/astra-control-center/index.html)
    to complete the setup and start managing applications.


    NOTE: The version listed under *Latest version* on this page might not
    reflect the actual version of NetApp Astra Control Center you are
    installing. The version in the file name of the Astra Control Center bundle
    that you download from the NetApp Support Site is the version of Astra
    Control Center that will be installed.
status:
  cleanup: {}
  conditions:
    - lastTransitionTime: '2023-11-21T16:18:08Z'
      lastUpdateTime: '2023-11-21T16:18:08Z'
      message: requirements not yet checked
      phase: Pending
      reason: RequirementsUnknown
    - lastTransitionTime: '2023-11-21T16:18:08Z'
      lastUpdateTime: '2023-11-21T16:18:08Z'
      message: one or more requirements couldn't be found
      phase: Pending
      reason: RequirementsNotMet
    - lastTransitionTime: '2023-11-21T16:18:09Z'
      lastUpdateTime: '2023-11-21T16:18:09Z'
      message: 'all requirements found, attempting install'
      phase: InstallReady
      reason: AllRequirementsMet
    - lastTransitionTime: '2023-11-21T16:18:09Z'
      lastUpdateTime: '2023-11-21T16:18:09Z'
      message: waiting for install components to report healthy
      phase: Installing
      reason: InstallSucceeded
    - lastTransitionTime: '2023-11-21T16:18:09Z'
      lastUpdateTime: '2023-11-21T16:18:10Z'
      message: >-
        installing: waiting for deployment acc-operator-controller-manager to
        become ready: waiting for spec update of deployment
        "acc-operator-controller-manager" to be observed...
      phase: Installing
      reason: InstallWaiting
    - lastTransitionTime: '2023-11-21T16:18:50Z'
      lastUpdateTime: '2023-11-21T16:18:50Z'
      message: install strategy completed with no errors
      phase: Succeeded
      reason: InstallSucceeded
  lastTransitionTime: '2023-11-21T16:18:50Z'
  lastUpdateTime: '2023-11-21T16:18:50Z'
  message: install strategy completed with no errors
  phase: Succeeded
  reason: InstallSucceeded
  requirementStatus:
    - group: operators.coreos.com
      kind: ClusterServiceVersion
      message: CSV minKubeVersion (1.19.0) less than server version (v1.26.9+07c0911)
      name: acc-operator.v23.10.0
      status: Present
      version: v1alpha1
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      message: CRD is present and Established condition is true
      name: astracontrolcenters.astra.netapp.io
      status: Present
      uuid: 12297a62-8493-4cd0-88f5-76004d1e868f
      version: v1
    - dependents:
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["get","list","watch","create","update","patch","delete"],"apiGroups":["","coordination.k8s.io"],"resources":["configmaps","leases"]}
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            namespaced
            rule:{"verbs":["create","patch"],"apiGroups":[""],"resources":["events"]}
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: 'cluster rule:{"verbs":["*"],"apiGroups":["*"],"resources":["*"]}'
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            cluster
            rule:{"verbs":["create"],"apiGroups":["authentication.k8s.io"],"resources":["tokenreviews"]}
          status: Satisfied
          version: v1
        - group: rbac.authorization.k8s.io
          kind: PolicyRule
          message: >-
            cluster
            rule:{"verbs":["create"],"apiGroups":["authorization.k8s.io"],"resources":["subjectaccessreviews"]}
          status: Satisfied
          version: v1
      group: ''
      kind: ServiceAccount
      message: ''
      name: default
      status: Present
      version: v1
