kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pure-claim-block
  labels:
    app: nginx # Example binding to application
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: sc-portworx-fa-direct-access