apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-registry-pvc
  nameSpace: openshift-image-registry
spec:
  StorageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 300Gi
  volumeName: image-registry-pv