apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-registry-pv
  nameSpace: openshift-image-registry
  labels:
    name: image-registry-pv
spec:
  storageClassName: "nfs-client"
  claimRef:
    name: image-registry-pvc
    namespace: openshift-image-registry
  capacity:
    storage: 200Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /media/ocpprod-image-registry
    server: k8bastion.ps.labs.local
  persistentVolumeReclaimPolicy: Retain
